// Code generated by "stringer -type=ImageInitializationErrorType"; DO NOT EDIT.

package wasmvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedImageError-0]
	_ = x[UnknownImageType-1]
	_ = x[FileImageOtherError-2]
	_ = x[ImageSizeRequired-3]
	_ = x[ImageSizeTooLargeForConfig-4]
	_ = x[ImageSizeTooLargeForMemory-5]
	_ = x[ImageInitArrayLargerThanConfig-6]
	_ = x[SparseEntryOutOfBounds-7]
	_ = x[SparseEntryMemoryOverwrite-8]
}

const _ImageInitializationErrorType_name = "UndefinedImageErrorUnknownImageTypeFileImageOtherErrorImageSizeRequiredImageSizeTooLargeForConfigImageSizeTooLargeForMemoryImageInitArrayLargerThanConfigSparseEntryOutOfBoundsSparseEntryMemoryOverwrite"

var _ImageInitializationErrorType_index = [...]uint8{0, 19, 35, 54, 71, 97, 123, 153, 175, 201}

func (i ImageInitializationErrorType) String() string {
	if i >= ImageInitializationErrorType(len(_ImageInitializationErrorType_index)-1) {
		return "ImageInitializationErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImageInitializationErrorType_name[_ImageInitializationErrorType_index[i]:_ImageInitializationErrorType_index[i+1]]
}
