// Code generated by "stringer -type=ImageType"; DO NOT EDIT.

package wasmvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[File-1]
	_ = x[Array-2]
	_ = x[Empty-3]
	_ = x[SparseArray-4]
}

const _ImageType_name = "UnknownFileArrayEmptySparseArray"

var _ImageType_index = [...]uint8{0, 7, 11, 16, 21, 32}

func (i ImageType) String() string {
	if i >= ImageType(len(_ImageType_index)-1) {
		return "ImageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ImageType_name[_ImageType_index[i]:_ImageType_index[i+1]]
}
