// Code generated by "stringer -type=ValueStackEntryType"; DO NOT EDIT.

package wasmvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TYPE_I32-0]
	_ = x[TYPE_F32-1]
	_ = x[TYPE_I64-2]
	_ = x[TYPE_F64-3]
}

const _ValueStackEntryType_name = "TYPE_I32TYPE_F32TYPE_I64TYPE_F64"

var _ValueStackEntryType_index = [...]uint8{0, 8, 16, 24, 32}

func (i ValueStackEntryType) String() string {
	if i < 0 || i >= ValueStackEntryType(len(_ValueStackEntryType_index)-1) {
		return "ValueStackEntryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueStackEntryType_name[_ValueStackEntryType_index[i]:_ValueStackEntryType_index[i+1]]
}
