// Code generated by "stringer -type=VMInitializationErrorType"; DO NOT EDIT.

package wasmvm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedVMInitError-0]
	_ = x[VMConfigInternalError-1]
	_ = x[VMConfigRequired-2]
	_ = x[VMImageError-3]
	_ = x[MissingSizeOrFlatMemory-4]
	_ = x[StrictModeAttemptRing0Reconfigure-5]
}

const _VMInitializationErrorType_name = "UndefinedVMInitErrorVMConfigInternalErrorVMConfigRequiredVMImageErrorMissingSizeOrFlatMemoryStrictModeAttemptRing0Reconfigure"

var _VMInitializationErrorType_index = [...]uint8{0, 20, 41, 57, 69, 92, 125}

func (i VMInitializationErrorType) String() string {
	if i >= VMInitializationErrorType(len(_VMInitializationErrorType_index)-1) {
		return "VMInitializationErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VMInitializationErrorType_name[_VMInitializationErrorType_index[i]:_VMInitializationErrorType_index[i+1]]
}
